baseURL = "https://www.jasongg.com"
languageCode = "en-us"
title = "Jason Gong"
theme = ["hugo-notice", "cactus"]
copyright = "Jason Gong"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writing"
url = "/posts"
weight = 2

[[menu.main]]
name = "Contact"
url = "https://twitter.com/jasgong"
weight = 3

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "dracula"
    tabWidth = 4

[params]

  colortheme = "dark" # dark, light, white, or classic
  rss = false # generate rss feed. default value is false
  showAllPostsArchive = true # default
  css = ["css/custom.css"]

  # Home page settings
  description = """
  Hello, I'm Jason!
  
  I write to reflect and share my thoughts on topics I find interesting. 

  I'm a recovering finance guy in tech. I've worked at a few startups, including [one that's profitable](https://www.jefit.com/), [one that was acquired](https://www.kite.com/blog/product/kite-is-saying-farewell/), [one that recently IPO'ed](https://www.affirm.com/), and even [one that I founded and left](https://github.com/firezone/firezone). My expertise is in product, go-to-market, and building adoption.

  If you enjoyed reading any of this, please let me know on [Twitter](https://twitter.com/jasgong)!

  If you're interested in working together, please reach out (jasongong00 at gmail dot com).
  """
  mainSection = "posts" # your main section
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = true # show tags overview by default.
  showProjectsList = true # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/gongjason" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = true # default
  showReadTime = true # default

  [params.comments]
    enabled = false # default

  # match to https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/gongjason"
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/jgong/"
  [[params.social]]
    name = "twitter"
    link = "https://twitter.com/jasgong"